version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: campus_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    image: node:20
    container_name: campus_server
    working_dir: /app/server
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/campus_essentials
      - JWT_SECRET=change_me
      - CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - STRIPE_SECRET_KEY=
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./server:/app/server
    depends_on:
      - mongo

  client:
    image: node:20
    container_name: campus_client
    working_dir: /app/client
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    volumes:
      - ./client:/app/client
    depends_on:
      - server

volumes:
  mongo_data:


